print("Welcome to the tip calculator.")
total = float(input("What was the total bill? "))
people = int(input("How many people to split the bill? "))
tip = int(input("How much tip would you like to give? 10, 12 or 15? "))
result = round((total + tip)/people)
print(f"Each person should pay: ${result}")
